# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82da97f980d975123526c31f1e234cd3d0ed1a16531f7925bda1555ba9237a4017d15d68f306490af8353d764ed977c4c4dcae2333155e383a90a3e7a6464bc1

test:
  secret_key_base: 92af6c08317ee7e63e35c7fd77d09c72f1a99cea2101fd060ee8c005203df81ec61e5d8e3861dc586f41f0651f2cabb454b1c0cd3fa0c21a6a94e8731a364b5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
