language:
  en: "en"
  vi: "vi"
default_value: 0
num_standard: 3
per_page: 10
round: 2
success: "success"
primary: "primary"
info: "info"
defaul: "default"
warning: "warning"
danger: "danger"
aspiration: "aspiration"
logo:
  size: 25
teacher: "teacher"
