language:
  en: "en"
  vi: "vi"
default_value: 0
num_standard: 3
per_page: 10
round: 2
aspiration: "aspiration"
logo:
  size: 25
  school: 70
teacher: "teacher"
student: "student"
admin: "admin"
min_name: 6
min_code: 3
college: "college"
intermediate: "intermediate"
warning: "warning"
danger: "danger"
success: "success"
info: "info"
primary: "primary"
basic: "basic"
default: "default"
min_content: 20
error_import: "error when input file"
error_data: "has user exist"
all: "all"
a4: "A4"
remarking: "remarking"
aspiration: "aspiration"
role:
  register: "register"
string_true: "1"
